//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryAnalyzer.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueryAnalyzer.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;Afghanistan&quot;,&quot;capital&quot;:&quot;Kabul&quot;,&quot;altSpellings&quot;:[&quot;AF&quot;,&quot;Afġānistān&quot;],&quot;relevance&quot;:&quot;0&quot;,&quot;region&quot;:&quot;Asia&quot;,&quot;subregion&quot;:&quot;Southern Asia&quot;,&quot;translations&quot;:{&quot;de&quot;:&quot;Afghanistan&quot;,&quot;es&quot;:&quot;Afganistán&quot;,&quot;fr&quot;:&quot;Afghanistan&quot;,&quot;ja&quot;:&quot;アフガニスタン&quot;,&quot;it&quot;:&quot;Afghanistan&quot;},&quot;population&quot;:26023100,&quot;latlng&quot;:[33.0,65.0],&quot;demonym&quot;:&quot;Afghan&quot;,&quot;area&quot;:652230.0,&quot;gini&quot;:27.8,&quot;timezones&quot;:[&quot;UTC+04:30&quot;],&quot;borders&quot;:[&quot;IRN&quot;,&quot;PAK&quot;,&quot;TKM&quot;,&quot;UZB&quot;,&quot;TJK&quot;,&quot;CHN&quot;],&quot;nativeName&quot;:&quot;افغانستان&quot;,&quot;callingCodes&quot;:[&quot;93&quot;],&quot;topLevelDomain&quot;:[&quot;.af&quot;],&quot;alpha2Code&quot;:&quot;AF&quot;,&quot;alpha3Code&quot;:&quot;A [rest of string was tru....
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CountrySchema {
            get {
                object obj = ResourceManager.GetObject("CountrySchema", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
